// Generated by CoffeeScript 1.7.1
(function() {
  var clickInput, file;

  file = require('file.js');

  clickInput = function(id) {
    var event;
    event = document.createEvent('MouseEvents');
    event.initMouseEvent('click');
    return document.getElementById(id).dispatchEvent(event);
  };

  $(window).bind('keydown', function(event) {
    if (event.ctrlKey || event.metaKey) {
      switch (String.fromCharCode(event.which).toLowerCase()) {
        case 's':
          event.preventDefault();
          return clickInput('save');
        case 'o':
          event.preventDefault();
          return clickInput('open');
      }
    }
  });

}).call(this);
