// Generated by CoffeeScript 1.7.1
(function() {
  var clickInput, file, gui, menu, win;

  file = require('file.js');

  gui = require('nw.gui');

  clickInput = function(id) {
    var event;
    event = document.createEvent('MouseEvents');
    event.initMouseEvent('click');
    return document.getElementById(id).dispatchEvent(event);
  };

  $(window).bind('keydown', function(event) {
    if (event.ctrlKey || event.metaKey) {
      switch (String.fromCharCode(event.which).toLowerCase()) {
        case 's':
          event.preventDefault();
          return clickInput('save');
        case 'o':
          event.preventDefault();
          return clickInput('open');
        case 'n':
          event.preventDefault();
          return gui.Window.open('index.html');
      }
    }
  });

  $('#open').change(function() {
    return file.open(this.value, document);
  });

  $('#save').change(function() {
    return file.save(this.value, document);
  });

  win = gui.Window.get();

  menu = new gui.Menu({
    type: 'menubar'
  });

  file = new gui.Menu();

  file.append(new gui.MenuItem({
    label: 'New',
    click: function() {
      return gui.Window.open('index.html');
    }
  }));

  file.append(new gui.MenuItem({
    type: 'separator'
  }));

  file.append(new gui.MenuItem({
    label: 'Close',
    click: function() {
      return gui.Window.get().close();
    }
  }));

  win.menu = menu;

  win.menu.insert(new gui.MenuItem({
    label: 'File',
    submenu: file
  }), 1);

}).call(this);
